# test in python
language: python
# python versions tested
python:
  - "3.5"
# enable the use of sudo
sudo: required
# operating system to use
os: linux
# distribution to use
dist: precise
# setting environment variables
env:
  - PACKAGE_VERSION=0.3.0 ARAKHNE_TEST_FIXTURES="arakhne/tests/fixtures"
# command to install dependencies
install:
  - pip install -r requirements/ci-testing.txt
  - pip install .
# command to run tests
script:
  - nose2
after_success:
  coveralls
notifications:
  on_success: never
  on_failure: never
