# test in python
language: python
# python versions tested
python:
  - "3.5"
# enable the use of sudo
sudo: required
# operating system to use
os: linux
# distribution to use
dist: precise
# setting environment variables
env:
  - PACKAGE_VERSION=0.2.1
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements/production.txt
  - pip install coveralls
# command to run tests
script:
  - cd arakhne
  - python -m 'from arakhne.get import Get'
  - python -m 'Get("latin").trainers()'
  - nosetests --with-coverage --cover-package=arakhne
after_success:
  coveralls
notifications:
  on_success: never
  on_failure: never
